#include "VoxelMatePCH.h"
#include "EngineGridTypes.h"

const FVoxelDatabaseVector::ValueType FVoxelDatabaseVector::ZeroValue = FVector::ZeroVector;
const FVoxelDatabaseVector4::ValueType FVoxelDatabaseVector4::ZeroValue = FVector4(0.0f, 0.0f, 0.0f, 0.0f);
const FVoxelDatabaseVector2D::ValueType FVoxelDatabaseVector2D::ZeroValue = FVector2D::ZeroVector;
const FVoxelDatabaseColor::ValueType FVoxelDatabaseColor::ZeroValue = FColor(0, 0, 0, 0);
const FVoxelDatabaseLinearColor::ValueType FVoxelDatabaseLinearColor::ZeroValue = FLinearColor(0.0f, 0.0f, 0.0f, 0.0f);
const FVoxelDatabasePackedNormal::ValueType FVoxelDatabasePackedNormal::ZeroValue = FPackedNormal::ZeroNormal;
const FVoxelDatabasePackedRGB10A2N::ValueType FVoxelDatabasePackedRGB10A2N::ZeroValue = FPackedRGB10A2N(511, 511, 511, 511); //TODO confirm this works as ZeroVector
const FVoxelDatabasePackedRGBA16N::ValueType FVoxelDatabasePackedRGBA16N::ZeroValue = FPackedRGBA16N(32767, 32767, 32767, 32767); //TODO confirm this works as ZeroVector
const FVoxelDatabaseIntPoint::ValueType FVoxelDatabaseIntPoint::ZeroValue = FIntPoint::ZeroValue;
const FVoxelDatabaseIntVector::ValueType FVoxelDatabaseIntVector::ZeroValue = FIntVector::ZeroValue;
const FVoxelDatabaseFloatRange::ValueType FVoxelDatabaseFloatRange::ZeroValue = FFloatRange::Empty();
const FVoxelDatabaseInt32Range::ValueType FVoxelDatabaseInt32Range::ZeroValue = FInt32Range::Empty();
const FVoxelDatabaseFloatInterval::ValueType FVoxelDatabaseFloatInterval::ZeroValue = FFloatInterval(0.0f, 0.0f);
const FVoxelDatabaseInt32Interval::ValueType FVoxelDatabaseInt32Interval::ZeroValue = FInt32Interval(0, 0);
const FVoxelDatabaseFloatRangeBound::ValueType FVoxelDatabaseFloatRangeBound::ZeroValue = FFloatRangeBound(0.0f);
const FVoxelDatabaseInt32RangeBound::ValueType FVoxelDatabaseInt32RangeBound::ZeroValue = FInt32RangeBound(0.0f);
const FVoxelDatabaseTwoVectors::ValueType FVoxelDatabaseTwoVectors::ZeroValue = FTwoVectors(FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue);
const FVoxelDatabasePlane::ValueType FVoxelDatabasePlane::ZeroValue = FPlane::ZeroVector;
const FVoxelDatabaseRotator::ValueType FVoxelDatabaseRotator::ZeroValue = FRotator::ZeroRotator;
const FVoxelDatabaseQuat::ValueType FVoxelDatabaseQuat::ZeroValue = FQuat(FVoxelDatabaseRotator::ZeroValue);
const FVoxelDatabaseBox::ValueType FVoxelDatabaseBox::ZeroValue = FBox(FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue);
const FVoxelDatabaseBox2D::ValueType FVoxelDatabaseBox2D::ZeroValue = FBox2D(FVoxelDatabaseVector2D::ZeroValue, FVoxelDatabaseVector2D::ZeroValue);
const FVoxelDatabaseBoxSphereBounds::ValueType FVoxelDatabaseBoxSphereBounds::ZeroValue = FBoxSphereBounds(FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue, 0.0f);
const FVoxelDatabaseOrientedBox::ValueType FVoxelDatabaseOrientedBox::ZeroValue = FOrientedBox();
const FVoxelDatabaseMatrix::ValueType FVoxelDatabaseMatrix::ZeroValue = FMatrix(FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue);
const FVoxelDatabaseInterpCurvePointFloat::ValueType FVoxelDatabaseInterpCurvePointFloat::ZeroValue = FInterpCurvePointFloat(0.0f, 0.0f);
const FVoxelDatabaseInterpCurveFloat::ValueType FVoxelDatabaseInterpCurveFloat::ZeroValue = FInterpCurveFloat();
const FVoxelDatabaseInterpCurvePointVector2D::ValueType FVoxelDatabaseInterpCurvePointVector2D::ZeroValue = FInterpCurvePointVector2D(0.0f, FVoxelDatabaseVector2D::ZeroValue);
const FVoxelDatabaseInterpCurveVector2D::ValueType FVoxelDatabaseInterpCurveVector2D::ZeroValue = FInterpCurveVector2D();
const FVoxelDatabaseInterpCurvePointVector::ValueType FVoxelDatabaseInterpCurvePointVector::ZeroValue = FInterpCurvePointVector(0.0f, FVoxelDatabaseVector::ZeroValue);
const FVoxelDatabaseInterpCurveVector::ValueType FVoxelDatabaseInterpCurveVector::ZeroValue = FInterpCurveVector();
const FVoxelDatabaseInterpCurvePointQuat::ValueType FVoxelDatabaseInterpCurvePointQuat::ZeroValue = FInterpCurvePointQuat(0.0f, FVoxelDatabaseQuat::ZeroValue);
const FVoxelDatabaseInterpCurveQuat::ValueType FVoxelDatabaseInterpCurveQuat::ZeroValue = FInterpCurveQuat();
const FVoxelDatabaseInterpCurvePointTwoVectors::ValueType FVoxelDatabaseInterpCurvePointTwoVectors::ZeroValue = FInterpCurvePointTwoVectors(0.0f, FVoxelDatabaseTwoVectors::ZeroValue);
const FVoxelDatabaseInterpCurveTwoVectors::ValueType FVoxelDatabaseInterpCurveTwoVectors::ZeroValue = FInterpCurveTwoVectors();
const FVoxelDatabaseInterpCurvePointLinearColor::ValueType FVoxelDatabaseInterpCurvePointLinearColor::ZeroValue = FInterpCurvePointLinearColor(0.0f, FVoxelDatabaseLinearColor::ZeroValue);
const FVoxelDatabaseInterpCurveLinearColor::ValueType FVoxelDatabaseInterpCurveLinearColor::ZeroValue = FInterpCurveLinearColor();
const FVoxelDatabaseTransform::ValueType FVoxelDatabaseTransform::ZeroValue = FTransform(FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue);
const FVoxelDatabaseRandomStream::ValueType FVoxelDatabaseRandomStream::ZeroValue = FRandomStream(0);
const FVoxelDatabaseDateTime::ValueType FVoxelDatabaseDateTime::ZeroValue = FDateTime(0, 0, 0);
const FVoxelDatabaseTimespan::ValueType FVoxelDatabaseTimespan::ZeroValue = FTimespan(0, 0, 0, 0, 0, 0);
const FVoxelDatabaseStringAssetReference::ValueType FVoxelDatabaseStringAssetReference::ZeroValue = FStringAssetReference();
const FVoxelDatabaseStringClassReference::ValueType FVoxelDatabaseStringClassReference::ZeroValue = FStringClassReference();
const FVoxelDatabaseString::ValueType FVoxelDatabaseString::ZeroValue = FString(TEXT(""));
const FVoxelDatabaseName::ValueType FVoxelDatabaseName::ZeroValue = FName();
const FVoxelDatabaseText::ValueType FVoxelDatabaseText::ZeroValue = FText::FromString(FVoxelDatabaseString::ZeroValue);
const FVoxelDatabaseAffineMap::ValueType FVoxelDatabaseAffineMap::ZeroValue = FAffineMap(FVoxelDatabasePlane::ZeroValue, FVoxelDatabasePlane::ZeroValue, FVoxelDatabasePlane::ZeroValue, FVoxelDatabasePlane::ZeroValue);
const FVoxelDatabaseUnitaryMap::ValueType FVoxelDatabaseUnitaryMap::ZeroValue = FUnitaryMap(FVoxelDatabaseVector::ZeroValue, 0.0f);
const FVoxelDatabaseScaleMap::ValueType FVoxelDatabaseScaleMap::ZeroValue = FScaleMap(FVoxelDatabaseVector::ZeroValue);
const FVoxelDatabaseUniformScaleMap::ValueType FVoxelDatabaseUniformScaleMap::ZeroValue = FUniformScaleMap(0.0f);
const FVoxelDatabaseTranslationMap::ValueType FVoxelDatabaseTranslationMap::ZeroValue = FTranslationMap(FVoxelDatabaseVector::ZeroValue);
const FVoxelDatabaseScaleTranslationMap::ValueType FVoxelDatabaseScaleTranslationMap::ZeroValue = FScaleTranslationMap(FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue);
const FVoxelDatabaseUniformScaleTranslationMap::ValueType FVoxelDatabaseUniformScaleTranslationMap::ZeroValue = FUniformScaleTranslationMap(0.0f, FVoxelDatabaseVector::ZeroValue);
const FVoxelDatabaseNonlinearFrustumMap::ValueType FVoxelDatabaseNonlinearFrustumMap::ZeroValue = FNonlinearFrustumMap(FVoxelDatabaseVector::ZeroValue, FVoxelDatabaseVector::ZeroValue, 0.0f, 0.0f);
