#include "VoxelMatePCH.h"
#include "GridTypes.h"

const FVoxelDatabaseBoolVoxel FVoxelDatabaseBoolVoxel::ZeroValue(false);
const FVoxelDatabaseDoubleVoxel FVoxelDatabaseDoubleVoxel::ZeroValue(0.0);
const FVoxelDatabaseFloatVoxel FVoxelDatabaseFloatVoxel::ZeroValue(0.0f);
const FVoxelDatabaseInt8Voxel FVoxelDatabaseInt8Voxel::ZeroValue(0);
const FVoxelDatabaseInt16Voxel FVoxelDatabaseInt16Voxel::ZeroValue(0);
const FVoxelDatabaseInt32Voxel FVoxelDatabaseInt32Voxel::ZeroValue(0);
const FVoxelDatabaseInt64Voxel FVoxelDatabaseInt64Voxel::ZeroValue(0);
const FVoxelDatabaseUInt8Voxel FVoxelDatabaseUInt8Voxel::ZeroValue(0);
const FVoxelDatabaseUInt16Voxel FVoxelDatabaseUInt16Voxel::ZeroValue(0);
const FVoxelDatabaseUInt32Voxel FVoxelDatabaseUInt32Voxel::ZeroValue(0);
const FVoxelDatabaseUInt64Voxel FVoxelDatabaseUInt64Voxel::ZeroValue(0);
const FVoxelDatabaseVectorVoxel FVoxelDatabaseVectorVoxel::ZeroValue(FVector::ZeroVector);
const FVoxelDatabaseVector4Voxel FVoxelDatabaseVector4Voxel::ZeroValue(FVector4(0.0f, 0.0f, 0.0f, 0.0f));
const FVoxelDatabaseVector2DVoxel FVoxelDatabaseVector2DVoxel::ZeroValue(FVector2D::ZeroVector);
const FVoxelDatabaseColorVoxel FVoxelDatabaseColorVoxel::ZeroValue(FColor(0, 0, 0, 0));
const FVoxelDatabaseLinearColorVoxel FVoxelDatabaseLinearColorVoxel::ZeroValue(FLinearColor(0.0f, 0.0f, 0.0f, 0.0f));
const FVoxelDatabasePackedNormalVoxel FVoxelDatabasePackedNormalVoxel::ZeroValue(FPackedNormal::ZeroNormal);
const FVoxelDatabasePackedRGB10A2NVoxel FVoxelDatabasePackedRGB10A2NVoxel::ZeroValue(FPackedRGB10A2N(511, 511, 511, 511)); //TODO confirm this works as ZeroVector
const FVoxelDatabasePackedRGBA16NVoxel FVoxelDatabasePackedRGBA16NVoxel::ZeroValue(FPackedRGBA16N(32767, 32767, 32767, 32767)); //TODO confirm this works as ZeroVector
const FVoxelDatabaseIntPointVoxel FVoxelDatabaseIntPointVoxel::ZeroValue(FIntPoint(0, 0));
const FVoxelDatabaseIntVectorVoxel FVoxelDatabaseIntVectorVoxel::ZeroValue(FIntVector(0, 0, 0));

const FVoxelDatabaseBoolMeta FVoxelDatabaseBoolMeta::ZeroValue(false);
const FVoxelDatabaseDoubleMeta FVoxelDatabaseDoubleMeta::ZeroValue(0.0);
const FVoxelDatabaseFloatMeta FVoxelDatabaseFloatMeta::ZeroValue(0.0f);
const FVoxelDatabaseInt8Meta FVoxelDatabaseInt8Meta::ZeroValue(0);
const FVoxelDatabaseInt16Meta FVoxelDatabaseInt16Meta::ZeroValue(0);
const FVoxelDatabaseInt32Meta FVoxelDatabaseInt32Meta::ZeroValue(0);
const FVoxelDatabaseInt64Meta FVoxelDatabaseInt64Meta::ZeroValue(0);
const FVoxelDatabaseUInt8Meta FVoxelDatabaseUInt8Meta::ZeroValue(0);
const FVoxelDatabaseUInt16Meta FVoxelDatabaseUInt16Meta::ZeroValue(0);
const FVoxelDatabaseUInt32Meta FVoxelDatabaseUInt32Meta::ZeroValue(0);
const FVoxelDatabaseUInt64Meta FVoxelDatabaseUInt64Meta::ZeroValue(0);
const FVoxelDatabaseVectorMeta FVoxelDatabaseVectorMeta::ZeroValue(FVector::ZeroVector);
const FVoxelDatabaseVector4Meta FVoxelDatabaseVector4Meta::ZeroValue(FVector4(0.0f, 0.0f, 0.0f, 0.0f));
const FVoxelDatabaseVector2DMeta FVoxelDatabaseVector2DMeta::ZeroValue(FVector2D::ZeroVector);
const FVoxelDatabaseColorMeta FVoxelDatabaseColorMeta::ZeroValue(FColor(0, 0, 0, 0));
const FVoxelDatabaseLinearColorMeta FVoxelDatabaseLinearColorMeta::ZeroValue(FLinearColor(0.0f, 0.0f, 0.0f, 0.0f));
const FVoxelDatabasePackedNormalMeta FVoxelDatabasePackedNormalMeta::ZeroValue(FPackedNormal::ZeroNormal);
const FVoxelDatabasePackedRGB10A2NMeta FVoxelDatabasePackedRGB10A2NMeta::ZeroValue(FPackedRGB10A2N(511, 511, 511, 511)); //TODO confirm this works as ZeroVector
const FVoxelDatabasePackedRGBA16NMeta FVoxelDatabasePackedRGBA16NMeta::ZeroValue(FPackedRGBA16N(32767, 32767, 32767, 32767)); //TODO confirm this works as ZeroVector
const FVoxelDatabaseIntPointMeta FVoxelDatabaseIntPointMeta::ZeroValue(FIntPoint(0, 0));
const FVoxelDatabaseIntVectorMeta FVoxelDatabaseIntVectorMeta::ZeroValue(FIntVector(0, 0, 0));
const FVoxelDatabaseFloatRangeMeta FVoxelDatabaseFloatRangeMeta::ZeroValue(FFloatRange::Empty());
const FVoxelDatabaseInt32RangeMeta FVoxelDatabaseInt32RangeMeta::ZeroValue(FInt32Range::Empty());
const FVoxelDatabaseFloatIntervalMeta FVoxelDatabaseFloatIntervalMeta::ZeroValue(FFloatInterval(0.0f, 0.0f));
const FVoxelDatabaseInt32IntervalMeta FVoxelDatabaseInt32IntervalMeta::ZeroValue(FInt32Interval(0, 0));
const FVoxelDatabaseFloatRangeBoundMeta FVoxelDatabaseFloatRangeBoundMeta::ZeroValue(FFloatRangeBound(0.0f));
const FVoxelDatabaseInt32RangeBoundMeta FVoxelDatabaseInt32RangeBoundMeta::ZeroValue(FInt32RangeBound(0.0f));
const FVoxelDatabaseTwoVectorsMeta FVoxelDatabaseTwoVectorsMeta::ZeroValue(FTwoVectors(FVector::ZeroVector, FVector::ZeroVector));
const FVoxelDatabasePlaneMeta FVoxelDatabasePlaneMeta::ZeroValue(FPlane(0.0f, 0.0f, 0.0f, 0.0f));
const FVoxelDatabaseRotatorMeta FVoxelDatabaseRotatorMeta::ZeroValue(FRotator::ZeroRotator);
const FVoxelDatabaseQuatMeta FVoxelDatabaseQuatMeta::ZeroValue(FQuat(FVector::ZeroVector, 0.0f));
const FVoxelDatabaseBoxMeta FVoxelDatabaseBoxMeta::ZeroValue(FBox(FVector::ZeroVector, FVector::ZeroVector));
const FVoxelDatabaseBox2DMeta FVoxelDatabaseBox2DMeta::ZeroValue(FBox2D(FVector2D::ZeroVector, FVector2D::ZeroVector));
const FVoxelDatabaseBoxSphereBoundsMeta FVoxelDatabaseBoxSphereBoundsMeta::ZeroValue(FBoxSphereBounds(FVector::ZeroVector, FVector::ZeroVector, 0.0f));
const FVoxelDatabaseOrientedBoxMeta FVoxelDatabaseOrientedBoxMeta::ZeroValue(MoveTemp(FOrientedBox()));
const FVoxelDatabaseMatrixMeta FVoxelDatabaseMatrixMeta::ZeroValue(FMatrix(FVector::ZeroVector, FVector::ZeroVector, FVector::ZeroVector, FVector::ZeroVector));
const FVoxelDatabaseInterpCurvePointFloatMeta FVoxelDatabaseInterpCurvePointFloatMeta::ZeroValue(FInterpCurvePointFloat(0.0f, 0.0f));
const FVoxelDatabaseInterpCurveFloatMeta FVoxelDatabaseInterpCurveFloatMeta::ZeroValue(MoveTemp(FInterpCurveFloat()));
const FVoxelDatabaseInterpCurvePointVector2DMeta FVoxelDatabaseInterpCurvePointVector2DMeta::ZeroValue(FInterpCurvePointVector2D(0.0f, FVector2D::ZeroVector));
const FVoxelDatabaseInterpCurveVector2DMeta FVoxelDatabaseInterpCurveVector2DMeta::ZeroValue(MoveTemp(FInterpCurveVector2D()));
const FVoxelDatabaseInterpCurvePointVectorMeta FVoxelDatabaseInterpCurvePointVectorMeta::ZeroValue(FInterpCurvePointVector(0.0f, FVector::ZeroVector));
const FVoxelDatabaseInterpCurveVectorMeta FVoxelDatabaseInterpCurveVectorMeta::ZeroValue(MoveTemp(FInterpCurveVector()));
const FVoxelDatabaseInterpCurvePointQuatMeta FVoxelDatabaseInterpCurvePointQuatMeta::ZeroValue(FInterpCurvePointQuat(0.0f, FQuat(FVector::ZeroVector, 0.0f)));
const FVoxelDatabaseInterpCurveQuatMeta FVoxelDatabaseInterpCurveQuatMeta::ZeroValue(MoveTemp(FInterpCurveQuat()));
const FVoxelDatabaseInterpCurvePointTwoVectorsMeta FVoxelDatabaseInterpCurvePointTwoVectorsMeta::ZeroValue(FInterpCurvePointTwoVectors(0.0f, FTwoVectors(FVector::ZeroVector, FVector::ZeroVector)));
const FVoxelDatabaseInterpCurveTwoVectorsMeta FVoxelDatabaseInterpCurveTwoVectorsMeta::ZeroValue(MoveTemp(FInterpCurveTwoVectors()));
const FVoxelDatabaseInterpCurvePointLinearColorMeta FVoxelDatabaseInterpCurvePointLinearColorMeta::ZeroValue(FInterpCurvePointLinearColor(0.0f, FLinearColor(0.0f, 0.0f, 0.0f, 0.0f)));
const FVoxelDatabaseInterpCurveLinearColorMeta FVoxelDatabaseInterpCurveLinearColorMeta::ZeroValue(MoveTemp(FInterpCurveLinearColor()));
const FVoxelDatabaseTransformMeta FVoxelDatabaseTransformMeta::ZeroValue(FTransform(FVector::ZeroVector, FVector::ZeroVector, FVector::ZeroVector, FVector::ZeroVector));
const FVoxelDatabaseRandomStreamMeta FVoxelDatabaseRandomStreamMeta::ZeroValue(FRandomStream(0));
const FVoxelDatabaseDateTimeMeta FVoxelDatabaseDateTimeMeta::ZeroValue(FDateTime(0));
const FVoxelDatabaseTimespanMeta FVoxelDatabaseTimespanMeta::ZeroValue(FTimespan(0));
const FVoxelDatabaseStringAssetReferenceMeta FVoxelDatabaseStringAssetReferenceMeta::ZeroValue(MoveTemp(FStringAssetReference()));
const FVoxelDatabaseStringClassReferenceMeta FVoxelDatabaseStringClassReferenceMeta::ZeroValue(MoveTemp(FStringClassReference()));
const FVoxelDatabaseStringMeta FVoxelDatabaseStringMeta::ZeroValue(TEXT(""));
const FVoxelDatabaseNameMeta FVoxelDatabaseNameMeta::ZeroValue(MoveTemp(FName()));
const FVoxelDatabaseTextMeta FVoxelDatabaseTextMeta::ZeroValue(FText::FromString(FString(TEXT(""))));
const FVoxelDatabaseAffineCoordinateTransformMeta FVoxelDatabaseAffineCoordinateTransformMeta::ZeroValue(MoveTemp(FAffineCoordinateTransform()));
const FVoxelDatabaseUnitaryCoordinateTransformMeta FVoxelDatabaseUnitaryCoordinateTransformMeta::ZeroValue(MoveTemp(FUnitaryCoordinateTransform()));
const FVoxelDatabaseScaleCoordinateTransformMeta FVoxelDatabaseScaleCoordinateTransformMeta::ZeroValue(MoveTemp(FScaleCoordinateTransform()));
const FVoxelDatabaseUniformScaleCoordinateTransformMeta FVoxelDatabaseUniformScaleCoordinateTransformMeta::ZeroValue(MoveTemp(FUniformScaleCoordinateTransform()));
const FVoxelDatabaseTranslationCoordinateTransformMeta FVoxelDatabaseTranslationCoordinateTransformMeta::ZeroValue(MoveTemp(FTranslationCoordinateTransform()));
const FVoxelDatabaseScaleTranslationCoordinateTransformMeta FVoxelDatabaseScaleTranslationCoordinateTransformMeta::ZeroValue(MoveTemp(FScaleTranslationCoordinateTransform()));
const FVoxelDatabaseUniformScaleTranslationCoordinateTransformMeta FVoxelDatabaseUniformScaleTranslationCoordinateTransformMeta::ZeroValue(MoveTemp(FUniformScaleTranslationCoordinateTransform()));
const FVoxelDatabaseNonlinearFrustumCoordinateTransformMeta FVoxelDatabaseNonlinearFrustumCoordinateTransformMeta::ZeroValue(MoveTemp(FNonlinearFrustumCoordinateTransform()));
